import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Plus } from "lucide-react";
import Link from "next/link";

// 1. İMPORTLARIMIZI EKLEYELİM
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { logout } from "@/app/actions/auth";
import { createClient } from "@/app/lib/supabase/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        {user && (
          <header className="absolute top-0 right-0 p-4 z-50">
            <form action={logout}>
              <button className="bg-white/80 hover:bg-white text-gray-600 px-4 py-2 rounded-full text-sm font-medium shadow-sm transition-all border border-gray-200 backdrop-blur-sm">
                Çıkış Yap
              </button>
            </form>
          </header>
        )}
        {children}

        {/* GLOBAL EKLE BUTONU - Sadece Ana Sayfada Göster (Layout'ta path kontrolü zor olduğu için burada bırakıp, kategori sayfasında üstüne binen butonu kullanabiliriz ama çirkin olur. En iyisi Layout'tan kaldırıp sayfalara eklemek.) */}
        {/* Şimdilik kaldırıyorum, çünkü her sayfaya (Home ve Category) özel ekledim/ekleyeceğim. */}
        {/* <Link href="/add"
          className="fixed bottom-8 right-8 bg-blue-600 hover:bg-blue-700 text-white p-4 rounded-full shadow-xl transition-transform hover:scale-110 flex items-center justify-center z-50"
        >
          <Plus className="w-8 h-8" />
        </Link> */}

        {/* 2. TOAST CONTAINER'I EN ALTA EKLEYELİM */}
        <ToastContainer
          position="bottom-center" // Mesajlar altta çıksın
          autoClose={3000} // 3 saniye sonra kapansın
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
